### ISSUE TITLE
Noobhub server alternative implementation

### ISSUE THREAD

**Issue by tst2005** [Overtorment/NoobHub#19]
Hello,

I planned to make lua code to support noobhub at server side, mainly for a love2d peer-to-peer app, maybe also for nginx (openresty).
I wonder if someone still use noobhub and are interested ?

Regards,

**Comment by Overtorment** [comment]
Lots of folks use Noobhub, but they all mostly need via-internet communication, in order to keep in a pool of players always ready to play. Peer2peer might be a cool but specific feature used by desktop apps.

Also, see pub/sub inside nginx would be interesting, but real life application is at question.
Cheers!

**Comment by tst2005** [comment]
Thanks for your answer!
If I'm not alone, I will keep my futur implementation(s) compatible with the current noobhub protocol.
